name: .NET Core API CI/CD

on:
  push:
    branches:
      - development
      - main

  pull_request:
    branches:
      - main

jobs:

  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: List Files
        run: |
          pwd
          find . -name "*.sln"
          find . -name "*.csproj"
      - name: Restore Packages
        run: dotnet restore DemoAutomapper.sln

      - name: Build
        run: dotnet build DemoAutomapper.sln --configuration Release --no-restore

      - name: Run Tests
        run: dotnet test DemoAutomapper.sln --no-build --configuration Release

      - name: Publish API
        run: dotnet publish DemoAutpmapper.csproj -c Release -o publish
     
      - name: Verify Publish Files
        run: |
          echo "Published files:"
          ls -la publish
          find publish -type f

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-api
          path: publish/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: dotnet-api
          path: publish
          
      - name: Verify Downloaded Files
        run: |
          echo "Downloaded files:"
          ls -la publish
          find publish -type f

      - name: Copy Files to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "publish/*"
          target: "/var/www/mymapperapi"

      - name: Restart Service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            sudo systemctl restart mymapperapi.service
            sudo systemctl status mymapperapi.service --no-pager
